# Generated by Django 2.1.5 on 2019-03-22 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DealerApp', '0002_auto_20190322_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Of_Bike', models.CharField(max_length=45)),
                ('Image', models.FileField(upload_to='')),
                ('Model', models.CharField(max_length=30)),
                ('Color', models.CharField(max_length=30)),
                ('Description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='postenquiry',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='postenquiry',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
